(function () {
  "use strict";
  const studio = window.DataHubStudio;
  if (!studio) return;
  const $ = selector => document.querySelector(selector);
  const $$ = selector => Array.from(document.querySelectorAll(selector));
  const esc = studio.escapeHtml;
  let marketFilter = "all", activeMeetingId = null, recognition = null;
  const connectors = [
    { id: "postgres", name: "PostgreSQL", category: "data", detail: "Read approved views through the secure gateway kit.", guide: "Create a read-only account, expose approved views through HTTPS, restrict CORS, and connect the JSON endpoint." },
    { id: "sqlserver", name: "SQL Server", category: "data", detail: "Connect operational or reporting databases safely.", guide: "Use a read-only login and a protected API using Microsoft Entra or your organization’s identity layer." },
    { id: "airtable", name: "Airtable", category: "business", detail: "Bring a shared view or gateway response into Studio.", guide: "For non-sensitive data use a read-only shared view. For private bases, keep the token behind a server gateway." },
    { id: "salesforce", name: "Salesforce", category: "business", detail: "Prepare CRM opportunities, accounts, and pipeline data.", guide: "Create a connected app with least-privilege scopes, perform OAuth on a server, and return only approved report fields." },
    { id: "hubspot", name: "HubSpot", category: "business", detail: "Analyze contacts, deals, campaigns, and funnel stages.", guide: "Use a private app token only in a server gateway. Limit scopes and expose a normalized read-only endpoint." },
    { id: "sharepoint", name: "SharePoint", category: "business", detail: "Refresh approved Microsoft 365 workbooks.", guide: "Register an Entra app, grant access to the required site only, retrieve the file with Microsoft Graph, and return CSV or JSON." },
    { id: "qualtrics", name: "Qualtrics", category: "research", detail: "Import survey responses and text for theme analysis.", guide: "Use a server-side API token, export only the target survey, and remove unnecessary identifying metadata." },
    { id: "ga4", name: "Google Analytics", category: "business", detail: "Analyze traffic, acquisition, engagement, and conversion.", guide: "Use the GA4 Data API through an authenticated gateway and define the approved dimensions and metrics." },
    { id: "snowflake", name: "Snowflake", category: "data", detail: "Query governed warehouse views with a limited role.", guide: "Create a read-only role and warehouse, use key-pair or OAuth authentication server-side, and expose parameterized approved queries." },
    { id: "redcap", name: "REDCap", category: "research", detail: "Prepare governed research exports without exposing tokens.", guide: "Keep the API token server-side, select the minimum fields, preserve project approvals, and return a de-identified response where possible." },
    { id: "forms", name: "Microsoft/Google Forms", category: "research", detail: "Analyze exported responses or a connected sheet.", guide: "Connect the response sheet when it is appropriate to share, or download Excel/CSV and import it locally." },
    { id: "rest", name: "REST API", category: "data", detail: "Connect any CORS-enabled CSV or JSON endpoint.", guide: "Use HTTPS, read-only credentials behind a gateway, a stable schema, pagination limits, and a last-good local snapshot." }
  ];
  const agents = [
    { id: "quinn", name: "Quinn", role: "Data quality reviewer" }, { id: "priya", name: "Priya", role: "Privacy and governance" }, { id: "felix", name: "Felix", role: "Forecasting and statistics" }, { id: "eva", name: "Eva", role: "Executive storytelling" }, { id: "theo", name: "Theo", role: "SQL and reproducibility" }
  ];

  function project() { return studio.state.project; }
  function data() { return studio.activeDataset(); }
  function uid(prefix) { return studio.uid(prefix); }
  function clone(value) { return JSON.parse(JSON.stringify(value)); }
  function columns(dataset = data()) { return dataset?.rows?.length ? Object.keys(dataset.rows[0]) : []; }
  function numberValue(value) { const parsed = Number(String(value ?? "").replace(/[$,%\s,]/g, "")); return Number.isFinite(parsed) ? parsed : null; }
  function numericFields(dataset = data()) { return columns(dataset).filter(column => { const values = dataset.rows.map(row => row[column]).filter(value => value !== "" && value != null); return values.length && values.filter(value => numberValue(value) !== null).length >= values.length * .75; }); }
  function format(value) { return Number.isFinite(value) ? new Intl.NumberFormat(undefined, { maximumFractionDigits: 2 }).format(value) : "—"; }
  function now() { return Date.now(); }
  function person() { return localStorage.getItem("datahub_chat_name") || "Project team"; }
  function download(name, content, type = "text/plain") { studio.download(name, content, type); }
  function slug(value) { return String(value || "signal-noir").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }
  function touch(action, entity = "Project", detail = "") { audit(action, entity, detail); studio.addActivity(action); studio.markDirty(); renderAll(); }
  function audit(action, entity, detail = "", actor = person()) { project().auditEvents.unshift({ id: uid("audit"), action, entity, detail, actor, at: now() }); project().auditEvents = project().auditEvents.slice(0, 500); }
  function notify(title, detail, type = "info") { project().notifications.unshift({ id: uid("notice"), title, detail, type, read: false, at: now() }); project().notifications = project().notifications.slice(0, 200); }
  function sync(collection, action, item) { window.DataHubCollaboration?.send("record", { projectId: project().id, collection, action, item: clone(item) }); }
  function upsert(collection, item) { const list = project()[collection]; if (!Array.isArray(list)) return; const index = list.findIndex(entry => entry.id === item.id); if (index >= 0) list[index] = item; else list.unshift(item); }
  function remove(collection, id) { project()[collection] = project()[collection].filter(item => item.id !== id); }
  function addRecord(collection, item, action) { project()[collection].unshift(item); sync(collection, "upsert", item); touch(action, collection, item.title || item.name || ""); }
  function setStatus(collection, id, status) { const item = project()[collection].find(entry => entry.id === id); if (!item) return; item.status = status; item.updatedAt = now(); sync(collection, "upsert", item); audit(`${collection} status changed`, item.title || item.name, status); studio.markDirty(); renderAll(); }

  function bindTabs() { $$('[data-ops-tab]').forEach(button => button.onclick = () => { $$('[data-ops-tab]').forEach(node => node.classList.toggle("active", node === button)); $$(".ops-panel").forEach(panel => panel.classList.toggle("active", panel.id === `ops-${button.dataset.opsTab}`)); }); }
  function fromChat(type, message) {
    if (type === "task") { const item = { id: uid("task"), title: message.text.slice(0, 160), owner: message.author, due: "", priority: "Medium", status: "Open", sourceMessageId: message.id, createdAt: now() }; addRecord("tasks", item, "Chat message converted to task"); notify("New task from chat", item.title, "assignment"); }
    if (type === "issue") { const item = { id: uid("issue"), title: message.text.slice(0, 160), owner: message.author, severity: "Medium", status: "Open", target: message.reference?.label || "Chat message", sourceMessageId: message.id, createdAt: now() }; addRecord("issues", item, "Chat message converted to data issue"); notify("New data issue", item.title, "issue"); }
    if (type === "decision") { const item = { id: uid("decision"), title: message.text.slice(0, 200), owner: message.author, evidence: message.reference?.label || "Project chat", status: "Recorded", sourceMessageId: message.id, createdAt: now() }; addRecord("decisions", item, "Chat message recorded as decision"); }
    studio.toast(`Created ${type} from chat.`);
  }
  window.DataHubOperations = { fromChat };

  function addTask() { const title = prompt("Task", "Review the current findings"); if (!title) return; const owner = prompt("Owner", person()) || "Unassigned", due = prompt("Due date (optional, YYYY-MM-DD)", "") || ""; const item = { id: uid("task"), title, owner, due, priority: "Medium", status: "Open", createdAt: now() }; addRecord("tasks", item, "Task created"); notify(`Task assigned to ${owner}`, title, "assignment"); }
  function renderTasks() { $("#task-board").innerHTML = project().tasks.length ? project().tasks.map(item => `<div class="ops-card"><div class="ops-card-head"><strong>${esc(item.title)}</strong><select data-task-status="${item.id}"><option ${item.status === "Open" ? "selected" : ""}>Open</option><option ${item.status === "In progress" ? "selected" : ""}>In progress</option><option ${item.status === "Blocked" ? "selected" : ""}>Blocked</option><option ${item.status === "Done" ? "selected" : ""}>Done</option></select></div><p>${esc(item.owner)}${item.due ? ` · due ${esc(item.due)}` : ""} · ${esc(item.priority)}</p><div class="ops-actions"><button data-delete-task="${item.id}">Remove</button></div></div>`).join("") : empty("No action items yet."); $$('[data-task-status]').forEach(select => select.onchange = () => setStatus("tasks", select.dataset.taskStatus, select.value)); $$('[data-delete-task]').forEach(button => button.onclick = () => { remove("tasks", button.dataset.deleteTask); sync("tasks", "delete", { id: button.dataset.deleteTask }); touch("Task removed", "Task"); }); }
  function addDecision() { const title = prompt("Decision", "Proceed with the recommended action"); if (!title) return; const evidence = prompt("Supporting evidence", project().stories[0]?.title || "Current project analysis") || "Current project"; addRecord("decisions", { id: uid("decision"), title, owner: person(), evidence, status: "Recorded", createdAt: now() }, "Decision recorded"); }
  function renderDecisions() { $("#decision-list").innerHTML = project().decisions.length ? project().decisions.map(item => `<div class="ops-card"><div class="ops-card-head"><strong>${esc(item.title)}</strong><small>${new Date(item.createdAt).toLocaleDateString()}</small></div><p>Evidence: ${esc(item.evidence)} · ${esc(item.owner)}</p><div class="ops-actions"><button data-decision-task="${item.id}">Create follow-up</button></div></div>`).join("") : empty("Pinned chat decisions and recorded outcomes appear here."); $$('[data-decision-task]').forEach(button => button.onclick = () => { const decision = project().decisions.find(item => item.id === button.dataset.decisionTask); if (decision) addRecord("tasks", { id: uid("task"), title: `Follow up: ${decision.title}`, owner: decision.owner, due: "", priority: "High", status: "Open", createdAt: now() }, "Decision follow-up created"); }); }
  function addIssue() { const title = prompt("Describe the issue", "Unexpected values need investigation"); if (!title) return; const target = prompt("Affected field, metric, or asset", columns()[0] || "Dataset") || "Dataset"; addRecord("issues", { id: uid("issue"), title, target, owner: "Unassigned", severity: "Medium", status: "Open", createdAt: now() }, "Data issue flagged"); notify("Data issue needs review", title, "issue"); }
  function renderIssues() { $("#issue-list").innerHTML = project().issues.length ? project().issues.map(item => `<div class="ops-card"><div class="ops-card-head"><strong>${esc(item.title)}</strong><select data-issue-status="${item.id}"><option ${item.status === "Open" ? "selected" : ""}>Open</option><option ${item.status === "Investigating" ? "selected" : ""}>Investigating</option><option ${item.status === "Resolved" ? "selected" : ""}>Resolved</option></select></div><p>${esc(item.target)} · ${esc(item.severity)} · ${esc(item.owner)}</p></div>`).join("") : empty("No open data issues."); $$('[data-issue-status]').forEach(select => select.onchange = () => setStatus("issues", select.dataset.issueStatus, select.value)); }
  function annotationOptions() { const values = [...(data() ? [["Dataset", data().name]] : []), ...columns().map(value => ["Column", value]), ...(data()?.rows || []).slice(0, 50).map((_, index) => ["Row", `Row ${index + 1}`]), ...project().metrics.map(item => ["Metric", item.name]), ...project().steps.map(item => ["Workflow", item.name]), ...project().stories.map(item => ["Story", item.title])]; $("#annotation-target").innerHTML = values.map(([type, label]) => `<option value="${esc(`${type}|${label}`)}">${esc(type)} · ${esc(label)}</option>`).join(""); }
  function addAnnotation() { const text = $("#annotation-text").value.trim(), [type, label] = $("#annotation-target").value.split("|"); if (!text || !label) return studio.toast("Choose evidence and add a comment."); addRecord("annotations", { id: uid("note"), type, label, text, author: person(), createdAt: now() }, "Evidence annotation added"); $("#annotation-text").value = ""; }
  function renderAnnotations() { $("#annotation-list").innerHTML = project().annotations.length ? project().annotations.map(item => `<div class="ops-card"><strong>${esc(item.type)} · ${esc(item.label)}</strong><p>${esc(item.text)}</p><small>${esc(item.author)} · ${new Date(item.createdAt).toLocaleString()}</small></div>`).join("") : empty("No evidence annotations yet."); }
  function renderNotifications() { $("#notification-list").innerHTML = project().notifications.length ? project().notifications.map(item => `<div class="ops-card ${item.read ? "" : "risk-medium"}"><div class="ops-card-head"><strong>${esc(item.title)}</strong><small>${item.read ? "Read" : "New"}</small></div><p>${esc(item.detail)}</p></div>`).join("") : empty("You are all caught up."); }

  function alertValue(rule) { const dataset = data(); if (!dataset) return { value: NaN, detail: "No data" }; const rows = dataset.rows, values = rows.map(row => numberValue(row[rule.field])).filter(value => value !== null); if (rule.operator === "missing") return { value: rows.length ? (rows.length - rows.filter(row => row[rule.field] !== "" && row[rule.field] != null).length) / rows.length * 100 : 0, detail: "missing rate" }; if (rule.operator === "change") { const mid = Math.floor(values.length / 2), before = values.slice(0, mid), after = values.slice(mid), a = before.reduce((x, y) => x + y, 0) / Math.max(1, before.length), b = after.reduce((x, y) => x + y, 0) / Math.max(1, after.length); return { value: a ? Math.abs((b - a) / a * 100) : 0, detail: "half-to-half change" }; } return { value: values.length ? values.reduce((a, b) => a + b, 0) / values.length : NaN, detail: "average" }; }
  function addAlert() { const name = $("#alert-name").value.trim(), field = $("#alert-field").value, threshold = Number($("#alert-value").value); if (!name || !field || !Number.isFinite(threshold)) return studio.toast("Add an alert name, field, and threshold."); addRecord("alertRules", { id: uid("alert"), name, field, operator: $("#alert-operator").value, threshold, active: true, lastTriggeredAt: null }, "Threshold alert created"); $("#alert-name").value = ""; }
  function evaluateAlerts() { let fired = 0; project().alertRules.filter(rule => rule.active).forEach(rule => { const result = alertValue(rule), hit = rule.operator === "lt" ? result.value < rule.threshold : result.value > rule.threshold; if (hit && (!rule.lastTriggeredAt || now() - rule.lastTriggeredAt > 60000)) { rule.lastTriggeredAt = now(); notify(rule.name, `${rule.field} ${result.detail} is ${format(result.value)}; threshold ${format(rule.threshold)}.`, "alert"); fired++; } }); audit("Alert rules evaluated", "Monitoring", `${fired} triggered`); studio.markDirty(); renderAll(); studio.toast(fired ? `${fired} alert${fired === 1 ? "" : "s"} triggered.` : "All thresholds are within range."); }
  function renderAlerts() { $("#alert-field").innerHTML = columns().map(field => `<option>${esc(field)}</option>`).join(""); $("#alert-list").innerHTML = project().alertRules.length ? project().alertRules.map(item => `<div class="ops-card"><strong>${esc(item.name)}</strong><p>${esc(item.field)} · ${esc(item.operator)} ${format(item.threshold)}</p><div class="ops-actions"><button data-toggle-alert="${item.id}">${item.active ? "Pause" : "Resume"}</button></div></div>`).join("") : empty("No monitoring rules yet."); $$('[data-toggle-alert]').forEach(button => button.onclick = () => { const rule = project().alertRules.find(item => item.id === button.dataset.toggleAlert); rule.active = !rule.active; studio.markDirty(); renderAlerts(); }); }

  function addCanvas(type) { let title, body; if (type === "metric") { const metric = project().metrics[0]; title = metric?.name || "Key metric"; body = metric?.formula || "Add a metric definition in Intelligence."; } else { title = prompt("Note title", "Working note"); if (!title) return; body = prompt("Note", "Add evidence or a question here") || ""; } const item = { id: uid("canvas"), type, title, body, x: 25 + project().canvasItems.length % 3 * 185, y: 25 + Math.floor(project().canvasItems.length / 3) * 115, updatedAt: now() }; addRecord("canvasItems", item, "Canvas card added"); }
  function renderCanvas() { const canvas = $("#shared-canvas"); canvas.innerHTML = project().canvasItems.map(item => `<div class="canvas-card" data-canvas-id="${item.id}" style="left:${item.x}px;top:${item.y}px"><button data-delete-canvas="${item.id}">×</button><strong>${esc(item.title)}</strong><span>${esc(item.body)}</span></div>`).join(""); $$('[data-delete-canvas]').forEach(button => button.onclick = event => { event.stopPropagation(); remove("canvasItems", button.dataset.deleteCanvas); sync("canvasItems", "delete", { id: button.dataset.deleteCanvas }); touch("Canvas card removed", "Canvas"); }); $$('[data-canvas-id]').forEach(card => { card.onpointerdown = event => { if (event.target.tagName === "BUTTON") return; const item = project().canvasItems.find(entry => entry.id === card.dataset.canvasId), startX = event.clientX, startY = event.clientY, baseX = item.x, baseY = item.y; card.setPointerCapture?.(event.pointerId); card.onpointermove = move => { item.x = Math.max(0, baseX + move.clientX - startX); item.y = Math.max(0, baseY + move.clientY - startY); card.style.left = `${item.x}px`; card.style.top = `${item.y}px`; }; card.onpointerup = () => { card.onpointermove = null; item.updatedAt = now(); studio.markDirty(); sync("canvasItems", "upsert", item); audit("Canvas card moved", item.title, `${Math.round(item.x)},${Math.round(item.y)}`); }; }; }); }
  function addRole() { const name = $("#role-name").value.trim(); if (!name) return studio.toast("Enter a teammate name."); const item = { id: uid("member"), name, role: $("#role-type").value }; project().members.push(item); sync("members", "upsert", item); notify(`${name} added as ${item.role}`, "Review their intended project access.", "access"); touch("Project role assigned", "Member", `${name} · ${item.role}`); $("#role-name").value = ""; }
  function renderRoles() { const permissions = { Owner: "Full project control", Analyst: "Edit data, analysis, and reports", Reviewer: "Comment and approve", Contributor: "Add data and notes", Viewer: "Read approved outputs" }; $("#role-list").innerHTML = project().members.length ? project().members.map(item => `<div class="ops-card"><div class="ops-card-head"><strong>${esc(item.name)}</strong><select data-member-role="${item.id}">${Object.keys(permissions).map(role => `<option ${role === item.role ? "selected" : ""}>${role}</option>`).join("")}</select></div><p>${esc(permissions[item.role] || "Project access")}</p></div>`).join("") : empty("No role assignments yet."); $$('[data-member-role]').forEach(select => select.onchange = () => { const item = project().members.find(member => member.id === select.dataset.memberRole); item.role = select.value; sync("members", "upsert", item); touch("Project role changed", "Member", `${item.name} · ${item.role}`); }); }

  function sharePayload(title) { return { title, project: project().name, status: project().projectStatus, goal: project().goal, metrics: project().metrics.map(item => ({ name: item.name, formula: item.formula })), story: project().stories[0] || null, portal: project().portalAssets, generatedAt: new Date().toISOString() }; }
  function bytesToBase64(bytes) { let binary = ""; bytes.forEach(byte => binary += String.fromCharCode(byte)); return btoa(binary); }
  async function createSecureShare() { const title = $("#share-title").value.trim() || `${project().name} read-only report`, pass = $("#share-passphrase").value; if (pass.length < 8) return studio.toast("Use a passphrase of at least eight characters."); if (!crypto.subtle) return studio.toast("Browser encryption is unavailable."); const salt = crypto.getRandomValues(new Uint8Array(16)), iv = crypto.getRandomValues(new Uint8Array(12)), material = await crypto.subtle.importKey("raw", new TextEncoder().encode(pass), "PBKDF2", false, ["deriveKey"]), key = await crypto.subtle.deriveKey({ name: "PBKDF2", salt, iterations: 150000, hash: "SHA-256" }, material, { name: "AES-GCM", length: 256 }, false, ["encrypt"]), cipher = new Uint8Array(await crypto.subtle.encrypt({ name: "AES-GCM", iv }, key, new TextEncoder().encode(JSON.stringify(sharePayload(title))))), bundle = { salt: bytesToBase64(salt), iv: bytesToBase64(iv), cipher: bytesToBase64(cipher) };
    const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${esc(title)}</title><style>body{margin:0;background:#f4f7fb;color:#172033;font:15px/1.6 Arial}main{max-width:850px;margin:8vh auto;padding:25px}section{padding:32px;background:white;border-radius:20px;box-shadow:0 18px 50px #00133c18}input,button{padding:12px;border-radius:9px;border:1px solid #dbe4ef}button{background:#0062f1;color:white;font-weight:bold}h1{color:#00133c;font-family:Georgia}article{margin-top:20px;padding-top:15px;border-top:1px solid #e5e7eb}</style></head><body><main><section id="lock"><h1>Protected Signal Noir report</h1><p>Enter the passphrase shared by the report owner.</p><input id="p" type="password"><button id="o">Open report</button><p id="e"></p></section><section id="r" hidden></section></main><script>const B=${JSON.stringify(bundle)};const b=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));o.onclick=async()=>{try{const m=await crypto.subtle.importKey('raw',new TextEncoder().encode(p.value),'PBKDF2',false,['deriveKey']);const k=await crypto.subtle.deriveKey({name:'PBKDF2',salt:b(B.salt),iterations:150000,hash:'SHA-256'},m,{name:'AES-GCM',length:256},false,['decrypt']);const d=JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:b(B.iv)},k,b(B.cipher))));lock.hidden=true;r.hidden=false;const add=(tag,text)=>{const n=document.createElement(tag);n.textContent=text;r.appendChild(n)};add('h1',d.title);add('p',d.goal||'Read-only project report');(d.metrics||[]).forEach(x=>{const a=document.createElement('article');const h=document.createElement('h3');h.textContent=x.name;const q=document.createElement('p');q.textContent=x.formula;a.append(h,q);r.appendChild(a)});(d.story?.beats||[]).forEach(x=>{add('h2',x.title);add('p',x.text)});add('small','Generated '+new Date(d.generatedAt).toLocaleString())}catch(x){e.textContent='Incorrect passphrase or damaged file.'}}<\/script></body></html>`;
    download(`${slug(title)}-secure.html`, html, "text/html"); audit("Encrypted share created", "Share", title); studio.markDirty(); studio.toast("Encrypted read-only share downloaded."); }
  function branchSnapshot() { const p = project(); return clone({ goal: p.goal, datasets: p.datasets, activeDatasetId: p.activeDatasetId, steps: p.steps, rules: p.rules, metrics: p.metrics, glossary: p.glossary, stories: p.stories, reportDesigns: p.reportDesigns }); }
  function createBranch() { const name = $("#branch-name").value.trim(); if (!name) return studio.toast("Name the branch."); const item = { id: uid("branch"), name, createdAt: now(), createdBy: person(), snapshot: branchSnapshot() }; project().branches.unshift(item); touch("Project branch created", "Branch", name); $("#branch-name").value = ""; }
  function restoreBranch(id) { const branch = project().branches.find(item => item.id === id); if (!branch) return; window.DataHubAnalyst?.checkpoint(`Before opening branch ${branch.name}`); Object.assign(project(), clone(branch.snapshot)); audit("Branch opened", "Branch", branch.name); studio.markDirty(); studio.renderAll(); studio.toast(`Opened branch “${branch.name}”.`); }
  function renderBranches() { $("#branch-list").innerHTML = project().branches.length ? project().branches.map(item => `<div class="ops-card"><strong>${esc(item.name)}</strong><p>${esc(item.createdBy)} · ${new Date(item.createdAt).toLocaleString()}</p><div class="ops-actions"><button data-open-branch="${item.id}">Open / merge</button></div></div>`).join("") : empty("No experimental branches yet."); $$('[data-open-branch]').forEach(button => button.onclick = () => restoreBranch(button.dataset.openBranch)); }
  function renderAudit() { const combined = [...project().auditEvents, ...project().activities.map((item, index) => ({ id: `activity_${index}`, at: Date.parse(item.at) || 0, actor: "Project", action: item.text, entity: "Activity", detail: "" }))].sort((a, b) => b.at - a.at).slice(0, 150); $("#audit-list").innerHTML = combined.length ? combined.map(item => `<div class="audit-row"><span>${item.at ? new Date(item.at).toLocaleString() : "Earlier"}</span><strong>${esc(item.actor)}</strong><span>${esc(item.action)}${item.detail ? ` · ${esc(item.detail)}` : ""}</span><span>${esc(item.entity)}</span></div>`).join("") : empty("No audited changes yet."); }

  function submitRequest(event) { event.preventDefault(); const title = $("#request-title").value.trim(), decision = $("#request-decision").value.trim(); if (!title || !decision) return studio.toast("Add the request and decision it supports."); const item = { id: uid("request"), title, decision, owner: $("#request-owner").value.trim() || "Unassigned", due: $("#request-due").value, output: $("#request-output").value, status: "Submitted", createdAt: now() }; addRecord("dataRequests", item, "Analysis request submitted"); notify("New analysis request", title, "request"); event.target.reset(); }
  function renderRequests() { $("#request-list").innerHTML = project().dataRequests.length ? project().dataRequests.map(item => `<div class="ops-card"><div class="ops-card-head"><strong>${esc(item.title)}</strong><select data-request-status="${item.id}"><option ${item.status === "Submitted" ? "selected" : ""}>Submitted</option><option ${item.status === "Scoping" ? "selected" : ""}>Scoping</option><option ${item.status === "In progress" ? "selected" : ""}>In progress</option><option ${item.status === "Delivered" ? "selected" : ""}>Delivered</option></select></div><p>${esc(item.decision)} · ${esc(item.output)}${item.due ? ` · ${esc(item.due)}` : ""}</p></div>`).join("") : empty("No analysis requests yet."); $$('[data-request-status]').forEach(select => select.onchange = () => setStatus("dataRequests", select.dataset.requestStatus, select.value)); }
  function createForm() { const name = $("#form-name").value.trim(), fields = $("#form-fields").value.split(",").map(value => value.trim()).filter(Boolean); if (!name || !fields.length) return studio.toast("Name the form and add at least one field."); addRecord("forms", { id: uid("form"), name, fields, createdAt: now() }, "Data collection form created"); $("#form-name").value = ""; $("#form-fields").value = ""; }
  function openForm(id) { const form = project().forms.find(item => item.id === id); if (!form) return; const target = $("#form-runner"); target.className = "form-runner"; target.innerHTML = `<strong>${esc(form.name)}</strong><form id="active-collection-form">${form.fields.map((field, index) => `<label>${esc(field)}<input data-form-field="${index}" required></label>`).join("")}<button class="button primary">Submit response</button></form><button class="button ghost" id="form-to-dataset-btn">Create dataset from responses</button>`; $("#active-collection-form").onsubmit = event => { event.preventDefault(); const values = {}; form.fields.forEach((field, index) => values[field] = $(`[data-form-field="${index}"]`).value); const response = { id: uid("response"), formId: form.id, values, submittedAt: now() }; project().formSubmissions.push(response); sync("formSubmissions", "upsert", response); touch("Form response collected", "Form", form.name); openForm(id); }; $("#form-to-dataset-btn").onclick = () => { const rows = project().formSubmissions.filter(item => item.formId === form.id).map(item => item.values); if (!rows.length) return studio.toast("Collect at least one response first."); const dataset = { id: uid("dataset"), name: `${form.name} responses`, rows: clone(rows), source: "Signal Noir collection form", importedAt: now() }; project().datasets.push(dataset); project().activeDatasetId = dataset.id; touch("Form responses converted to dataset", "Dataset", dataset.name); studio.renderAll(); }; }
  function renderForms() { $("#form-list").innerHTML = project().forms.length ? project().forms.map(item => `<div class="ops-card"><strong>${esc(item.name)}</strong><p>${item.fields.map(esc).join(" · ")} · ${project().formSubmissions.filter(response => response.formId === item.id).length} responses</p><div class="ops-actions"><button data-open-form="${item.id}">Open form</button></div></div>`).join("") : empty("No collection forms yet."); $$('[data-open-form]').forEach(button => button.onclick = () => openForm(button.dataset.openForm)); }
  function nextDelivery(date, frequency) { const next = new Date(`${date}T09:00:00`); if (frequency === "weekly") next.setDate(next.getDate() + 7); if (frequency === "monthly") next.setMonth(next.getMonth() + 1); if (frequency === "quarterly") next.setMonth(next.getMonth() + 3); return next.toISOString().slice(0, 10); }
  function addDelivery() { const name = $("#delivery-name").value.trim(), date = $("#delivery-date").value; if (!name || !date) return studio.toast("Name the delivery and choose its first date."); addRecord("deliveries", { id: uid("delivery"), name, format: $("#delivery-format").value, frequency: $("#delivery-frequency").value, nextDate: date, destination: $("#delivery-destination").value, runs: 0 }, "Report delivery scheduled"); }
  function csv(rows) { if (!rows.length) return ""; const fields = Object.keys(rows[0]), quote = value => `"${String(value ?? "").replace(/"/g, '""')}"`; return [fields.map(quote).join(","), ...rows.map(row => fields.map(field => quote(row[field])).join(","))].join("\n"); }
  function runDelivery(id, automatic = false) { const item = project().deliveries.find(entry => entry.id === id); if (!item) return; const dataset = data(), base = slug(item.name); if (automatic) { item.ready = true; item.runs++; item.lastRunAt = now(); item.nextDate = nextDelivery(item.nextDate, item.frequency); notify("Scheduled delivery ready", `${item.name} is prepared. Open Operations → Intake to export it.`, "delivery"); audit("Due delivery prepared on open", "Delivery", item.name); studio.markDirty(); renderAll(); return; } if (item.destination === "download") { if (item.format === "json") download(`${base}.json`, JSON.stringify(project(), null, 2), "application/json"); else if (item.format === "csv") { if (!dataset) return studio.toast("Select a dataset first."); download(`${base}.csv`, csv(dataset.rows), "text/csv"); } else { const story = project().stories[0], html = `<!doctype html><html><head><meta charset="utf-8"><title>${esc(item.name)}</title></head><body><h1>${esc(project().name)}</h1><p>${esc(project().goal)}</p>${story ? story.beats.map(beat => `<h2>${esc(beat.title)}</h2><p>${esc(beat.text)}</p>`).join("") : "<p>No story generated.</p>"}</body></html>`; download(`${base}.html`, html, "text/html"); } } else window.DataHubCollaboration?.draftMessage(`Scheduled delivery ready: ${item.name} (${item.format.toUpperCase()}) for ${project().name}.`); item.ready = false; item.runs++; item.lastRunAt = now(); if (!item.nextDate || item.nextDate <= new Date().toISOString().slice(0, 10)) item.nextDate = nextDelivery(item.nextDate || new Date().toISOString().slice(0, 10), item.frequency); notify("Scheduled delivery prepared", item.name, "delivery"); audit("Scheduled delivery run", "Delivery", item.name); studio.markDirty(); renderAll(); }
  function processDueDeliveries() { const today = new Date().toISOString().slice(0, 10); project()?.deliveries.filter(item => item.nextDate <= today).forEach(item => runDelivery(item.id, true)); }
  function renderDeliveries() { $("#delivery-list").innerHTML = project().deliveries.length ? project().deliveries.map(item => `<div class="ops-card"><strong>${esc(item.name)}${item.ready ? " · Ready" : ""}</strong><p>${esc(item.format.toUpperCase())} · ${esc(item.frequency)} · next ${esc(item.nextDate)}</p><div class="ops-actions"><button data-run-delivery="${item.id}">${item.ready ? "Export prepared report" : "Run now"}</button></div></div>`).join("") : empty("No scheduled deliveries."); $$('[data-run-delivery]').forEach(button => button.onclick = () => runDelivery(button.dataset.runDelivery)); }

  function lineageNodes() { const source = project().datasets.slice(0, 3).map(item => ({ type: "Source", label: item.name })), steps = project().steps.slice(0, 3).map(item => ({ type: "Transform", label: item.name })), metrics = project().metrics.slice(0, 3).map(item => ({ type: "Metric", label: item.name })), outputs = [...project().stories.slice(0, 1).map(item => ({ type: "Story", label: item.title })), ...project().decisions.slice(0, 2).map(item => ({ type: "Decision", label: item.title }))]; return [source, steps, metrics, outputs].filter(group => group.length); }
  function renderLineage() { const groups = lineageNodes(), width = Math.max(620, groups.length * 180), height = Math.max(260, Math.max(1, ...groups.map(group => group.length)) * 86 + 30); let nodes = "", edges = ""; groups.forEach((group, gi) => group.forEach((item, ni) => { const x = 20 + gi * 180, y = 30 + ni * 86; nodes += `<rect x="${x}" y="${y}" width="145" height="56" rx="11" fill="${gi === groups.length - 1 ? "#00133c" : "#eff6ff"}" stroke="#93c5fd"/><text x="${x + 10}" y="${y + 19}" fill="${gi === groups.length - 1 ? "white" : "#0062f1"}" font-size="9" font-weight="bold">${esc(item.type)}</text><text x="${x + 10}" y="${y + 37}" fill="${gi === groups.length - 1 ? "white" : "#334155"}" font-size="9">${esc(item.label.slice(0, 22))}</text>`; if (gi < groups.length - 1) edges += `<line x1="${x + 145}" y1="${y + 28}" x2="${x + 178}" y2="${30 + Math.min(ni, groups[gi + 1].length - 1) * 86 + 28}" stroke="#93c5fd" stroke-width="2"/>`; })); $("#lineage-map").innerHTML = groups.length ? `<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Project lineage graph">${edges}${nodes}</svg>` : empty("Add data and workflow steps to build lineage."); }
  function syncMetricRegistry() { project().metrics.forEach(metric => { if (!project().metricRegistry.some(item => item.metricId === metric.id)) project().metricRegistry.push({ id: uid("registry"), metricId: metric.id, name: metric.name, owner: "Unassigned", target: "", certification: "Draft", reviewDate: "" }); }); }
  function renderMetricRegistry() { syncMetricRegistry(); $("#metric-registry").innerHTML = project().metricRegistry.length ? project().metricRegistry.map(item => `<div class="ops-card"><div class="ops-card-head"><strong>${esc(item.name)}</strong><select data-metric-cert="${item.id}"><option ${item.certification === "Draft" ? "selected" : ""}>Draft</option><option ${item.certification === "Reviewed" ? "selected" : ""}>Reviewed</option><option ${item.certification === "Certified" ? "selected" : ""}>Certified</option></select></div><div class="ops-inline"><input data-metric-owner="${item.id}" value="${esc(item.owner)}" placeholder="Owner"><input data-metric-target="${item.id}" value="${esc(item.target)}" placeholder="Target"></div></div>`).join("") : empty("Create metrics in Intelligence to assign ownership."); $$('[data-metric-cert]').forEach(select => select.onchange = () => { const item = project().metricRegistry.find(entry => entry.id === select.dataset.metricCert); item.certification = select.value; audit("Metric certification changed", item.name, item.certification); studio.markDirty(); }); $$('[data-metric-owner]').forEach(input => input.onchange = () => { const item = project().metricRegistry.find(entry => entry.id === input.dataset.metricOwner); item.owner = input.value; studio.markDirty(); }); $$('[data-metric-target]').forEach(input => input.onchange = () => { const item = project().metricRegistry.find(entry => entry.id === input.dataset.metricTarget); item.target = input.value; studio.markDirty(); }); }
  function addKnowledge() { const title = $("#knowledge-title").value.trim(), content = $("#knowledge-content").value.trim(); if (!title || !content) return studio.toast("Add a title and approved guidance."); addRecord("knowledgeBase", { id: uid("knowledge"), title, type: $("#knowledge-type").value, content, owner: person(), updatedAt: now() }, "Knowledge article added"); $("#knowledge-title").value = ""; $("#knowledge-content").value = ""; }
  function renderKnowledge() { const query = $("#knowledge-search").value.toLowerCase(), items = project().knowledgeBase.filter(item => `${item.title} ${item.type} ${item.content}`.toLowerCase().includes(query)); $("#knowledge-list").innerHTML = items.length ? items.map(item => `<div class="ops-card"><div class="ops-card-head"><strong>${esc(item.title)}</strong><small>${esc(item.type)}</small></div><p>${esc(item.content)}</p><small>${esc(item.owner)}</small></div>`).join("") : empty(query ? "No matching knowledge." : "No approved knowledge yet."); }
  function projectHealth(p) { const checks = [p.datasets?.length, p.goal, p.rules?.length, p.glossary?.length || p.mappings?.length, p.metrics?.length, p.stories?.length || p.report, p.privacyFindings?.length || p.datasets?.some(item => item.redacted), ["Approved", "Published"].includes(p.projectStatus), p.members?.length, p.auditEvents?.length]; return Math.round(checks.filter(Boolean).length / checks.length * 100); }
  function renderHealth() { const projects = studio.state.projects.length ? studio.state.projects : [project()]; $("#health-center").innerHTML = projects.map(item => { const score = projectHealth(item); return `<div class="health-card"><strong>${esc(item.name)}</strong><span>${item.datasets?.length || 0} data · ${item.issues?.filter(issue => issue.status !== "Resolved").length || 0} open issues · ${esc(item.projectStatus || "Draft")}</span><div class="health-meter"><i style="width:${score}%"></i></div><span>${score}% ready</span></div>`; }).join(""); $("#ops-health-score").textContent = projectHealth(project()); }

  function runAgentCouncil() { const dataset = data(), numeric = numericFields(), findings = { quinn: project().rules.length ? `${project().rules.length} quality rules exist; ${project().issues.filter(item => item.status !== "Resolved").length} issues remain open.` : "No repeatable quality rules are defined yet.", priya: project().privacyFindings.length ? `${project().privacyFindings.length} sensitive-field findings require an explicit sharing decision.` : "No privacy scan evidence is recorded; run the scanner before publication.", felix: numeric.length ? `${numeric.length} measurable fields are available. Forecasts should document time order and scenario assumptions.` : "No reliable numeric measure was detected for forecasting or statistical testing.", eva: project().stories.length ? "The executive story includes evidence and limitations; tie the closing action to a named owner." : "Generate an executive story before presenting to leadership.", theo: project().steps.length ? `${project().steps.length} workflow steps are documented. Export code and record the source version for reproducibility.` : "The analysis has no repeatable workflow steps yet." };
    agents.forEach(agent => { const review = { id: uid("review"), agentId: agent.id, name: agent.name, role: agent.role, finding: findings[agent.id], status: /no |not |remain|require/i.test(findings[agent.id]) ? "Needs attention" : "Reviewed", at: now() }; project().agentReviews = project().agentReviews.filter(item => item.agentId !== agent.id); project().agentReviews.push(review); }); audit("Analytics agent council completed", "Agent review", `${dataset?.name || "No dataset"}`); studio.markDirty(); renderAgents(); }
  function renderAgents() { $("#agent-grid").innerHTML = agents.map(agent => { const review = project().agentReviews.find(item => item.agentId === agent.id); return `<div class="agent-card"><b>${agent.name} · ${agent.role}</b><span>${esc(review?.finding || "Ready to review this project independently.")}</span><span class="agent-status">${esc(review?.status || "Not run")}</span></div>`; }).join(""); }
  function startMeeting() { const title = $("#meeting-title").value.trim() || `${project().name} decision meeting`, agenda = $("#meeting-agenda").value.split("\n").map(value => value.trim()).filter(Boolean); const item = { id: uid("meeting"), title, agenda, notes: "", startedAt: now(), endedAt: null, owner: person() }; project().meetings.unshift(item); activeMeetingId = item.id; audit("Meeting started", "Meeting", title); studio.markDirty(); renderMeeting(); }
  function renderMeeting() { const item = project().meetings.find(entry => entry.id === activeMeetingId) || project().meetings.find(entry => !entry.endedAt); const target = $("#meeting-room"); if (!item) { target.className = "meeting-room empty"; target.textContent = "Start a meeting to capture notes, actions, questions, and decisions."; return; } activeMeetingId = item.id; const elapsed = Math.floor(((item.endedAt || now()) - item.startedAt) / 1000), minutes = String(Math.floor(elapsed / 60)).padStart(2, "0"), seconds = String(elapsed % 60).padStart(2, "0"); target.className = "meeting-room"; target.innerHTML = `<div class="meeting-timer">${minutes}:${seconds}</div><strong>${esc(item.title)}</strong><p>${item.agenda.map(esc).join(" · ") || "Open agenda"}</p><textarea id="active-meeting-notes" class="meeting-notes" rows="7" placeholder="Capture questions, evidence, actions, and decisions…">${esc(item.notes)}</textarea><div class="action-row"><button id="meeting-save-btn" class="button ghost">Save notes</button><button id="meeting-task-btn" class="button ghost">Notes → task</button><button id="meeting-decision-btn" class="button ghost">Notes → decision</button><button id="meeting-end-btn" class="button primary">End &amp; export minutes</button></div>`; $("#meeting-save-btn").onclick = () => { item.notes = $("#active-meeting-notes").value; studio.markDirty(); audit("Meeting notes saved", "Meeting", item.title); }; $("#meeting-task-btn").onclick = () => { item.notes = $("#active-meeting-notes").value; addRecord("tasks", { id: uid("task"), title: item.notes.slice(0, 160) || `Follow up from ${item.title}`, owner: person(), due: "", priority: "Medium", status: "Open", createdAt: now() }, "Meeting action created"); }; $("#meeting-decision-btn").onclick = () => { item.notes = $("#active-meeting-notes").value; addRecord("decisions", { id: uid("decision"), title: item.notes.slice(0, 200) || `Decision from ${item.title}`, owner: person(), evidence: item.title, status: "Recorded", createdAt: now() }, "Meeting decision recorded"); }; $("#meeting-end-btn").onclick = () => endMeeting(item); }
  function endMeeting(item) { item.notes = $("#active-meeting-notes").value; item.endedAt = now(); const text = `# ${item.title}\n\nDate: ${new Date(item.startedAt).toLocaleString()}\nOwner: ${item.owner}\n\n## Agenda\n${item.agenda.map(value => `- ${value}`).join("\n")}\n\n## Notes\n${item.notes}\n\n## Decisions\n${project().decisions.filter(value => value.createdAt >= item.startedAt).map(value => `- ${value.title}`).join("\n") || "- None recorded"}\n\n## Actions\n${project().tasks.filter(value => value.createdAt >= item.startedAt).map(value => `- ${value.title} — ${value.owner}`).join("\n") || "- None recorded"}`; download(`${slug(item.title)}-minutes.md`, text, "text/markdown"); audit("Meeting ended", "Meeting", item.title); activeMeetingId = null; studio.markDirty(); renderMeeting(); }

  function addPortalAsset() { const title = $("#portal-asset-title").value.trim(); if (!title) return studio.toast("Name the approved asset."); addRecord("portalAssets", { id: uid("asset"), type: $("#portal-asset-type").value, title, status: "Published", summary: project().goal || "Approved analytics asset", createdAt: now() }, "Portal asset published"); $("#portal-asset-title").value = ""; }
  function renderPortal() { const cards = project().portalAssets.map(item => `<div class="portal-card"><strong>${esc(item.title)}</strong><span>${esc(item.type)} · ${esc(item.status)}</span><div class="ops-actions"><button data-remove-asset="${item.id}">Remove</button></div></div>`).join(""); $("#portal-assets").innerHTML = cards || empty("Add approved assets to the organization portal."); $$('[data-remove-asset]').forEach(button => button.onclick = () => { remove("portalAssets", button.dataset.removeAsset); touch("Portal asset removed", "Portal"); }); const brand = project().branding?.name || "Signal Noir"; $("#portal-preview").innerHTML = `<h4>${esc(brand)} analytics portal</h4><p>Approved evidence for your organization.</p><div class="portal-preview-grid">${project().portalAssets.map(item => `<div class="portal-preview-card"><strong>${esc(item.title)}</strong><small>${esc(item.type)}</small></div>`).join("") || "No published assets yet."}</div>`; }
  function exportPortal() { const brand = project().branding?.name || "Signal Noir", assets = project().portalAssets, html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${esc(brand)} Analytics Portal</title><style>body{margin:0;background:#f4f7fb;color:#172033;font:15px/1.5 Arial}header{padding:55px max(25px,8vw);background:#00133c;color:white}main{max-width:1050px;margin:auto;padding:35px 25px;display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:14px}article{padding:20px;background:white;border:1px solid #dfe7f1;border-radius:15px}h1{font-family:Georgia}</style></head><body><header><h1>${esc(brand)} Analytics Portal</h1><p>Approved dashboards, reports, metrics, and datasets</p></header><main>${assets.map(item => `<article><small>${esc(item.type)}</small><h2>${esc(item.title)}</h2><p>${esc(item.summary)}</p></article>`).join("")}</main></body></html>`; download(`${slug(brand)}-analytics-portal.html`, html, "text/html"); audit("Analytics portal exported", "Portal", `${assets.length} assets`); }
  function renderMarket() { const installed = new Set(project().installedConnectors.map(item => item.id)), visible = connectors.filter(item => marketFilter === "all" || item.category === marketFilter); $("#connector-market").innerHTML = visible.map(item => `<div class="connector-card"><em>${esc(item.category)}</em><b>${esc(item.name)}</b><span>${esc(item.detail)}</span><button class="button ${installed.has(item.id) ? "ghost" : "primary"}" data-install-connector="${item.id}">${installed.has(item.id) ? "Setup guide" : "Install guide"}</button></div>`).join(""); $$('[data-install-connector]').forEach(button => button.onclick = () => installConnector(button.dataset.installConnector)); }
  function installConnector(id) { const item = connectors.find(entry => entry.id === id); if (!item) return; if (!project().installedConnectors.some(entry => entry.id === id)) { project().installedConnectors.push({ id, installedAt: now() }); audit("Connector guide installed", "Connector", item.name); studio.markDirty(); } studio.dialog(`<span class="eyebrow">Connector setup</span><h2>${esc(item.name)}</h2><p class="muted">${esc(item.detail)}</p><div class="lab-result"><strong>Safe setup path</strong><br>${esc(item.guide)}</div><p class="fine-print">Credentials should stay in a protected server or OAuth flow, never inside an exported Signal Noir project.</p>`); renderMarket(); }

  function voiceSetup() { const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition; const button = $("#voice-start-btn"); if (!SpeechRecognition) { button.disabled = true; $("#voice-status").textContent = "Speech recognition is not available here. Voice playback may still work."; return; } recognition = new SpeechRecognition(); recognition.continuous = false; recognition.interimResults = true; recognition.onstart = () => { button.classList.add("listening"); button.textContent = "● Listening…"; }; recognition.onend = () => { button.classList.remove("listening"); button.textContent = "● Start listening"; }; recognition.onerror = () => { $("#voice-status").textContent = "Voice recognition stopped. Check microphone permission."; }; recognition.onresult = event => { const transcript = Array.from(event.results).map(result => result[0].transcript).join(" "); $("#voice-status").textContent = transcript; if (event.results[event.results.length - 1].isFinal) routeVoice(transcript); }; }
  function routeVoice(text) { const target = $("#voice-target").value; if (target === "chat") window.DataHubCollaboration?.draftMessage(text); if (target === "task") addRecord("tasks", { id: uid("task"), title: text, owner: person(), due: "", priority: "Medium", status: "Open", createdAt: now() }, "Voice task created"); if (target === "request") addRecord("dataRequests", { id: uid("request"), title: text.slice(0, 120), decision: text, owner: person(), due: "", output: "Executive report", status: "Submitted", createdAt: now() }, "Voice request created"); if (target === "meeting") { const meeting = project().meetings.find(item => !item.endedAt); if (meeting) { meeting.notes += `${meeting.notes ? "\n" : ""}${text}`; studio.markDirty(); renderMeeting(); } else studio.toast("Start a meeting first."); } }
  function readBriefing() { if (!window.speechSynthesis) return studio.toast("Speech playback is unavailable."); const openTasks = project().tasks.filter(item => item.status !== "Done").length, issues = project().issues.filter(item => item.status !== "Resolved").length, text = `${project().name}. ${project().goal || "No decision goal is documented."} There are ${openTasks} open tasks, ${issues} unresolved data issues, ${project().decisions.length} recorded decisions, and the project status is ${project().projectStatus}.`; speechSynthesis.cancel(); speechSynthesis.speak(new SpeechSynthesisUtterance(text)); }

  function empty(text) { return `<div class="ops-card"><p>${esc(text)}</p></div>`; }
  function handleRemote(type, payload) { if (type !== "record" || payload?.projectId !== project()?.id) return; const allowed = new Set(["tasks", "decisions", "issues", "annotations", "canvasItems", "members", "dataRequests", "formSubmissions"]); if (!allowed.has(payload.collection) || !payload.item?.id) return; if (payload.action === "delete") remove(payload.collection, payload.item.id); else upsert(payload.collection, payload.item); audit("Live collaborative update", payload.collection, payload.item.title || payload.item.name || "record", "Teammate"); notify("Live project update", `${payload.collection} was updated by a teammate.`, "collaboration"); studio.markDirty(); renderAll(); }

  function renderAll() { if (!project()) return; renderTasks(); renderDecisions(); renderIssues(); annotationOptions(); renderAnnotations(); renderNotifications(); renderAlerts(); renderCanvas(); renderRoles(); renderBranches(); renderAudit(); renderRequests(); renderForms(); renderDeliveries(); renderLineage(); renderMetricRegistry(); renderKnowledge(); renderHealth(); renderAgents(); renderMeeting(); renderPortal(); renderMarket(); }
  function bind() {
    bindTabs(); $("#add-task-btn").onclick = addTask; $("#add-decision-btn").onclick = addDecision; $("#add-issue-btn").onclick = addIssue; $("#add-annotation-btn").onclick = addAnnotation; $("#mark-notifications-btn").onclick = () => { project().notifications.forEach(item => item.read = true); studio.markDirty(); renderNotifications(); }; $("#evaluate-alerts-btn").onclick = evaluateAlerts; $("#add-alert-btn").onclick = addAlert;
    $("#add-canvas-note-btn").onclick = () => addCanvas("note"); $("#add-canvas-metric-btn").onclick = () => addCanvas("metric"); $("#add-role-btn").onclick = addRole; $("#create-secure-share-btn").onclick = createSecureShare; $("#create-branch-btn").onclick = createBranch;
    $("#request-form").onsubmit = submitRequest; $("#create-form-btn").onclick = createForm; $("#add-delivery-btn").onclick = addDelivery; $("#add-knowledge-btn").onclick = addKnowledge; $("#knowledge-search").oninput = renderKnowledge;
    $("#run-agent-council-btn").onclick = runAgentCouncil; $("#start-meeting-btn").onclick = startMeeting; $("#add-portal-asset-btn").onclick = addPortalAsset; $("#export-portal-btn").onclick = exportPortal; $$('[data-market-filter]').forEach(button => button.onclick = () => { marketFilter = button.dataset.marketFilter; $$('[data-market-filter]').forEach(node => node.classList.toggle("active", node === button)); renderMarket(); });
    voiceSetup(); $("#voice-start-btn").onclick = () => recognition?.start(); $("#voice-read-btn").onclick = readBriefing; window.DataHubCollaboration?.subscribe(handleRemote); window.addEventListener("datahub:project-render", renderAll); setInterval(() => { if (activeMeetingId) renderMeeting(); }, 1000); renderAll(); setTimeout(processDueDeliveries, 200);
  }
  bind();
})();
