(function(){
  "use strict";
  const studio=window.DataHubStudio;if(!studio)return;
  const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s)),esc=studio.escapeHtml;
  let answer=null;
  function project(){const p=studio.state.project;for(const k of ["dataQuestions","pinnedInsights"])if(!Array.isArray(p[k]))p[k]=[];return p;}
  function norm(v){return String(v||"").toLowerCase().replace(/[_-]+/g," ").replace(/[^a-z0-9 ]/g,"").replace(/\s+/g," ").trim()}
  function numeric(ds,c){const v=ds.rows.map(r=>r[c]).filter(x=>x!==""&&x!=null);return v.length&&v.filter(x=>Number.isFinite(Number(x))).length/v.length>.8}
  function category(ds,c){const v=ds.rows.map(r=>r[c]).filter(x=>x!==""&&x!=null);return v.length&&new Set(v.map(String)).size<=Math.min(40,v.length*.5)}
  function find(q,cols){return cols.map(c=>({c,n:norm(c)})).filter(x=>x.n&&norm(q).includes(x.n)).sort((a,b)=>b.n.length-a.n.length)[0]?.c||null}
  function fmt(v,c){const n=Number(v);if(!Number.isFinite(n))return String(v??"—");return /revenue|sales|cost|price|profit|income|amount|budget|spend/.test(norm(c))?n.toLocaleString(undefined,{style:"currency",currency:"USD",maximumFractionDigits:2}):n.toLocaleString(undefined,{maximumFractionDigits:2})}
  function analyze(question){
    const ds=studio.activeDataset();if(!ds)throw Error("Add or select a dataset first.");const q=norm(question),nums=ds.columns.filter(c=>numeric(ds,c)),cats=ds.columns.filter(c=>category(ds,c));
    const op=/average|avg|mean/.test(q)?"average":/minimum|min |lowest/.test(q)?"minimum":/maximum|max |highest/.test(q)?"maximum":/count|how many|number of/.test(q)?"count":"total";
    const by=q.match(/\bby\s+(.+)$/)?.[1],group=by?find(by,cats):(/breakdown|compare|top|largest/.test(q)?find(q,cats):null),metric=find(q,nums)||nums[0]||null,operation=!metric&&op!=="count"?"count":op,rows=[...ds.rows];
    const calc=list=>{if(operation==="count")return list.length;const v=list.map(r=>Number(r[metric])).filter(Number.isFinite);if(!v.length)return 0;if(operation==="average")return v.reduce((a,b)=>a+b,0)/v.length;if(operation==="minimum")return Math.min(...v);if(operation==="maximum")return Math.max(...v);return v.reduce((a,b)=>a+b,0)};
    const value=calc(rows),sets={};if(group)rows.forEach(r=>{const k=String(r[group]??"Blank");(sets[k]||=[]).push(r)});const breakdown=Object.entries(sets).map(([label,list])=>({label,value:calc(list)})).sort((a,b)=>b.value-a.value).slice(0,10);
    const label={total:"Total",average:"Average",minimum:"Minimum",maximum:"Maximum",count:"Count"}[operation],formula=operation==="count"?"COUNT(rows)":operation.toUpperCase()+"("+metric+")"+(group?" GROUP BY "+group:"");
    return{id:studio.uid("answer"),question,datasetId:ds.id,dataset:ds.name,title:fmt(value,metric),subtitle:label+" "+(operation==="count"?"records":metric)+(group?" · grouped by "+group:""),formula,metric,breakdown,rows:rows.slice(0,100),at:new Date().toLocaleString()};
  }
  function render(a){answer=a;const max=Math.max(1,...a.breakdown.map(x=>Math.abs(x.value)));$("#ask-data-result").className="ask-data-result";$("#ask-data-result").innerHTML='<div class="answer-head"><div><small>'+esc(a.dataset)+'</small><strong>'+esc(a.title)+'</strong><p>'+esc(a.subtitle)+'</p></div><div class="answer-actions"><button class="icon-button" id="inspect-answer-btn">Source rows</button><button class="icon-button" id="pin-answer-btn">Pin</button><button class="icon-button" id="share-answer-btn">Discuss</button></div></div>'+(a.breakdown.length?'<div class="answer-chart">'+a.breakdown.map(x=>'<div class="answer-bar"><span>'+esc(x.label)+'</span><div class="answer-bar-track"><div class="answer-bar-fill" style="width:'+Math.max(2,Math.abs(x.value)/max*100)+'%"></div></div><strong>'+esc(fmt(x.value,a.metric))+'</strong></div>').join("")+'</div>':"")+'<div class="answer-explain">'+esc(a.formula)+' · '+a.rows.length.toLocaleString()+' source rows available</div>';
    $("#inspect-answer-btn").onclick=inspect;$("#pin-answer-btn").onclick=pin;$("#share-answer-btn").onclick=share;
  }
  function ask(q){q=String(q||"").trim();if(!q)return;try{const a=analyze(q);project().dataQuestions.unshift({...a,rows:a.rows.slice(0,20)});project().dataQuestions=project().dataQuestions.slice(0,20);studio.addActivity("Asked the data: "+q.slice(0,70));studio.saveProject(true);render(a)}catch(e){$("#ask-data-result").className="ask-data-result empty";$("#ask-data-result").textContent=e.message}}
  function inspect(){if(!answer)return;const ds=studio.activeDataset(),cols=ds.columns.slice(0,8);studio.dialog('<span class="eyebrow">Answer evidence</span><h2>'+esc(answer.title)+'</h2><p class="muted">'+esc(answer.formula)+'</p><div class="table-shell" style="max-height:430px;margin-top:16px"><table><thead><tr>'+cols.map(c=>'<th>'+esc(c)+'</th>').join("")+'</tr></thead><tbody>'+answer.rows.slice(0,30).map(r=>'<tr>'+cols.map(c=>'<td>'+esc(String(r[c]??""))+'</td>').join("")+'</tr>').join("")+'</tbody></table></div>')}
  function pin(){if(!answer)return;project().pinnedInsights.unshift({id:answer.id,title:answer.title,subtitle:answer.subtitle,dataset:answer.dataset,at:answer.at});project().pinnedInsights=project().pinnedInsights.slice(0,24);studio.markDirty();studio.saveProject(true);renderPins();studio.toast("Answer pinned.")}
  function share(){if(answer&&window.DataHubCollaboration)window.DataHubCollaboration.draftMessage('Data answer: “'+answer.question+'”\n'+answer.title+' — '+answer.subtitle+'\nCalculation: '+answer.formula)}
  function suggestions(){const ds=studio.activeDataset(),n=$("#ask-data-suggestions");if(!ds){n.innerHTML="";return}const empty=$("#ask-data-result.empty");if(empty)empty.textContent="Ask a question above or choose a suggested analysis to get started.";const num=ds.columns.find(c=>numeric(ds,c)),cat=ds.columns.find(c=>category(ds,c)),q=[num&&"Total "+num,num&&"Average "+num,num&&cat&&"Total "+num+" by "+cat,cat&&"Count by "+cat,"How many records?"].filter(Boolean);n.innerHTML=q.map(x=>'<button type="button" data-suggest="'+esc(x)+'">'+esc(x)+'</button>').join("");$$('[data-suggest]').forEach(b=>b.onclick=()=>{$("#ask-data-input").value=b.dataset.suggest;ask(b.dataset.suggest)})}
  function renderPins(){const items=project().pinnedInsights,panel=$("#pinned-insights-panel");panel.hidden=!items.length;$("#pinned-insights-count").textContent=items.length+" pinned";$("#pinned-insights").innerHTML=items.map(x=>'<article class="pinned-insight"><button data-unpin="'+x.id+'">×</button><small>'+esc(x.dataset)+'</small><strong>'+esc(x.title)+'</strong><span>'+esc(x.subtitle)+'</span></article>').join("");$$('[data-unpin]').forEach(b=>b.onclick=()=>{project().pinnedInsights=items.filter(x=>x.id!==b.dataset.unpin);studio.markDirty();renderPins()})}
  function pulse(){const p=project(),ds=studio.activeDataset(),ready=[!!ds,p.steps.length>0,p.rules.length>0,!!p.report,p.tasks.length>0||p.decisions.length>0],score=ready.filter(Boolean).length*20,open=p.tasks.filter(t=>!/[Dd]one|[Cc]omplete/.test(t.status||"")).length;const items=[[!!ds,ds?ds.name:"No active dataset",ds?ds.rows.length+" rows · "+ds.columns.length+" fields":"Add a source","data"],[p.rules.length>0,p.rules.length?"Quality rules active":"Quality is not monitored",p.rules.length+" rules configured","quality"],[!!p.report,p.report?"Report ready":"Report has not been generated",p.report?"Presentation mode is available":"Build the story","report"],[open===0,open?open+" open action items":"No open action items","Review ownership","operations"]];$("#project-pulse").innerHTML='<div class="pulse-score"><div class="pulse-ring" style="--score:'+score+'"><strong>'+score+'</strong></div><div><strong>Project readiness</strong><span>'+ready.filter(Boolean).length+' of 5 foundations ready</span></div></div>'+items.map(i=>'<div class="pulse-item '+(i[0]?"":"warn")+'"><i></i><div><strong>'+esc(i[1])+'</strong><span>'+esc(i[2])+'</span></div><button data-pulse="'+i[3]+'">Open</button></div>').join("");$$('[data-pulse]').forEach(b=>b.onclick=()=>studio.showView(b.dataset.pulse))}
  function focus(force){const on=force===undefined?!document.body.classList.contains("focus-mode"):force;document.body.classList.toggle("focus-mode",on);$("#focus-mode-btn").classList.toggle("focus-exit",on);$("#focus-mode-btn").innerHTML=on?"<span>×</span>Exit focus":"<span>◇</span>Focus"}
  $("#ask-data-form").onsubmit=e=>{e.preventDefault();ask($("#ask-data-input").value)};$("#refresh-pulse-btn").onclick=pulse;$("#focus-mode-btn").onclick=()=>focus();document.addEventListener("keydown",e=>{if(e.key==="Escape"&&document.body.classList.contains("focus-mode"))focus(false)});window.addEventListener("datahub:project-render",()=>{suggestions();pulse();renderPins()});suggestions();pulse();renderPins();
})();
